[project]
authors = ["Modular <hello@modular.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "frontend"
platforms = ["linux-64", "osx-arm64", "linux-aarch64"]
version = "0.0.0"

[tasks]
dev-frontend = { cmd = "npm run dev", depends-on = ["build"] }
frontend = { cmd = "npm run start", depends-on = ["build"] }
build = { cmd = "npm run build", depends-on = ["init"] }
init = "npm install next"

[dependencies]
nodejs = ">=22.12.0,<22.13"
