packages:
    - apps/*
    - packages/*

catalog:
    '@ai-sdk/openai': ^2.0.23
    '@ai-sdk/react': ^2.0.30
    '@mantine/core': ^7.17.8
    '@mantine/dropzone': ^7.17.8
    '@mantine/hooks': ^7.17.8
    '@microsoft/fetch-event-source': ^2.0.1
    '@tabler/icons-react': ^3.34.1
    '@types/node': ^20
    '@types/react': ^18
    '@types/react-dom': ^18
    ai: ^5.0.28
    nanoid: ^5.1.5
    openai: ^5.20.2
    streamdown: ^1.3.0
    swr: ^2.3.6
    typescript: ^5
