[project]
authors = ["Modular <hello@modular.com>"]
channels = [
    "conda-forge",
    "https://conda.modular.com/max-nightly",
]
description = "Add a short description here"
name = "frontend"
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]
version = "0.0.0"

[tasks]
app = "honcho start"
clean = "honcho -f Procfile.clean start"
tests = "echo 'test passed'"
demo = "honcho -f Procfile.demo start"

[dependencies]
docker-compose = ">=2.29"
bash = ">=5.2.21,<6"
honcho = ">=2.0.0,<3"
