max-serve-llm: (magic global install max-pipelines && magic global update max-pipelines); MAX_SERVE_PORT=8010 HUGGING_FACE_HUB_TOKEN=$(cat backend/.env | grep HUGGING_FACE_HUB_TOKEN | cut -d '=' -f2) max-pipelines serve --model-path modularai/Llama-3.1-8B-Instruct-GGUF --max-length 2048
max-serve-embedding: (magic global install max-pipelines && magic global update max-pipelines); MAX_SERVE_PORT=7999 HUGGING_FACE_HUB_TOKEN=$(cat backend/.env | grep HUGGING_FACE_HUB_TOKEN | cut -d '=' -f2) max-pipelines serve --model-path sentence-transformers/all-mpnet-base-v2
backend: cd backend && magic run backend
frontend: cd frontend && magic run frontend
